site_name: OSG Research Faciliation
site_url: https://opensciencegrid.org/research-facilitation/
repo_url: https://github.com/opensciencegrid/research-facilitation/
google_analytics: ['UA-69012-29', 'opensciencegrid.github.io']
theme:
  name: material
  custom_dir: osgthedocs
  favicon: 'img/favicon.ico'

extra_css:
  - css/extra.css

nav:
- Home: 'index.md'
- General:
  - 'CVMFS': 'general/cvmfs.md'
- Accounts and Groups:
  - 'General': 'accounts-and-projects/general.md'
  - 'Accounts': 'accounts-and-projects/accounts.md'
  - 'Projects': 'accounts-and-projects/projects.md'
  - 'GoSync3': 'accounts-and-projects/gosync3.md'
- Midscale Engagements:
  - SPT:
    - 'General': 'midscale-engagements/spt/general.md'
    - 'CVMFS': 'midscale-engagements/spt/cvmfs.md'
  - VERITAS:
    - 'General': 'midscale-engagements/veritas/general.md'
    - 'CVMFS': 'midscale-engagements/veritas/cvmfs.md'
  - XENON:
    - 'General': 'midscale-engagements/xenon/general.md'
    - 'CVMFS': 'midscale-engagements/xenon/cvmfs.md'
- Documentation:
  - 'Freshdesk': 'documentation/freshdesk.md'
  - 'Support Tickets': 'documentation/support-tickets.md'

markdown_extensions:
  - admonition
  - codehilite
  - toc:
     permalink: True
